<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>The Fault in Our Stars | Official Movie Site | #TFIOS</title>
<style>
body{
	font-family:Arial, Helvetica, sans-serif;
	font-size:12px;
	
	}
	.content-text{
		max-width:1000px;
		margin: 0 auto;
		}
</style>
</head>

<body>
<div class="content-text">
<p align="center"><strong>THE FAULT IN OUR STARS HOME ENTERTAINMENT  SWEEPSTAKES</strong><br />
  <a name="_DV_M5" id="_DV_M5"></a><strong>OFFICIAL RULES</strong></p>
<p><strong>&nbsp;</strong></p>
<p><a name="_DV_M6" id="_DV_M6"></a><strong>NO  PURCHASE NECESSARY. MAKING A PURCHASE WILL NOT IMPROVE YOUR CHANCES OF WINNING.<a name="_DV_M7" id="_DV_M7"></a></strong><br />
  <strong>PROMOTION  DESCRIPTION:</strong> <em>The Fault In Our Stars </em>Home Entertainment  Sweepstakes (the &ldquo;Promotion&rdquo;) begins on August 26, 2014 at 12:00:00 AM Eastern  Time (ET) and ends <a name="_DV_M8" id="_DV_M8"></a>September 30, 2014 at 11:59:59 PM ET  (the<strong> </strong>&quot;Promotion Period&quot;).  Each entrant (each, a &ldquo;Participant&rdquo;) unconditionally accepts and agrees to  comply with and abide by these Official Rules and the decisions of Twentieth  Century Fox Home Entertainment LLC (the &quot;Sponsor&quot;) which shall be  final and binding in all respects. <a name="_DV_M9" id="_DV_M9"></a><strong></strong><br />
  <strong>PROMOTION ELIGIBILITY:</strong> The Promotion  is open only to legal residents of the 50 United States, District Columbia  (U.S.), and Canada (excluding Quebec) age 21 or older at the time of entry, or  if a Canadian resident, who are above the age of majority in the province or  territory in which they reside at the time of entry. Void outside these  geographic areas and wherever else prohibited by law.  Employees, officers and directors of Sponsor, it&rsquo;s respective parents,  subsidiaries, affiliates, independent sales distributors, prize providers,  advertising and promotional agencies (collectively &ldquo;Sweepstakes Entities&rdquo;) (and  immediate family members or those living in the same household with such  individuals), are not eligible to participate.  All federal, state provincial and local laws and regulations apply.  <strong></strong><br />
  <a name="_DV_M10" id="_DV_M10"></a><strong>HOW TO ENTER: </strong>To enter the  Sweepstakes, visit <a href="http://www.mylittleinfinity.com">www.mylittleinfinity.com</a>  (the &ldquo;Website&rdquo;) during the Promotion  Period and follow all entry instructions to complete the entry process  (the &ldquo;Entry&rdquo;)<a name="_DV_M16" id="_DV_M16"></a>.  <strong>Limit: One (1)  Entry per person during the Promotion Period, </strong>regardless  of whether entrant has more than one email address<strong>.</strong>  All methods of entry have an equal chance of  winning. All entries become the property of the Sponsor and will not be  acknowledged or returned.  Online  entrants are subject to all notices posted online including but not limited to  the Sponsor&rsquo;s Privacy Policy.  </p>
<p><strong>PRIZE DETAILS  /APPROXIMATE </strong><strong>RETAIL VALUE</strong> (&ldquo;ARV&rdquo;): <a name="_DV_M18" id="_DV_M18"></a>There will be one (1) Grand Prize consisting of a trip  for one (1) (Grand Prize Winner and his/her guest), to Amsterdam.  The Amsterdam  Grand Prize trip includes the following:</p>
<ul type="disc">
  <li>Orange Tulip Delivery to       the winner&rsquo;s home address, to include prize details and itinerary.<u></u></li>
  <li>Round-trip coach airfare       for two (2) to Amsterdam, from a       US major airport. <u></u></li>
  <li>Roundtrip Airport       Transfers in Amsterdam, in a private luxury vehicle; <u></u></li>
  <li>Three (3) night hotel       accommodation at the Sandton Hotel De Filosoof.<u></u></li>
  <li>Entrance for two (2)       people to the historic landmark of Anne Frank&rsquo;s House.<u></u></li>
  <li>$150 to spend on the       perfect dress or outfit.<u></u></li>
  <li>VIP two (2) hour       candlelight cruise for tow (2), along Amsterdam&rsquo;s famous canals on a       glass-roofed boat, with soft drinks and snacks, and fantastic waterfront       views.<u></u></li>
  <li>Dinner for two (2) at       Restaurant De Kas: (ARV $250), including roundtrip restaurant transfers.<u></u></li>
</ul>
<p><strong>TOTAL ARV of Grand Prize: $4,975.00 </strong></p>
<p><strong>ODDS:</strong> Odds of  winning depend on the number of eligible entries received during the Promotion  Period.<a name="_DV_M25" id="_DV_M25"></a><br />
  <strong></strong><br />
  <strong>WINNER  SELECTION:</strong> Winner  will be selected in a random drawing on or about October 7, 2014, from among  all eligible entries received during the Promotion Period,  conducted by an independent judging agency and whose decisions are final. <br />
  <br />
  <strong>WINNER  NOTIFICATION:</strong>  <strong>Grand Prize winner will be  confirmed via email, mail and/or phone. </strong><br />
  <strong>US residents </strong>will  be required<strong> to  sign and return, within ten (10) days of notification, an Affidavit of  Eligibility, a Liability Waiver, a W-9 Form and where allowable, a Publicity  Release (collectively, &quot;the Releases&quot;). </strong>These releases  will require the Winner to furnish his/her Social Security Number for the sole  purpose of tax reporting, as required by law.  <br />
  <strong>Canadian residents</strong> will be  required <strong>within ten (10) days of  notification</strong>: (a) to <strong>sign and return, an Declaration a  Publicity Release </strong>and (b) to correctly answer a time-limited  mathematical skill-testing question via return mail or email without assistance  or mechanical aid <strong>(collectively, &quot;the  Releases&quot;)</strong>.  <br />
  <br />
  Failure to return the documents and/or information requested by a winner, or  the return of any prize or prize notification as undeliverable, or if a Winner  is found to be ineligible or otherwise not in compliance with these Official  Rules, the prize will be forfeited and an alternate potential winner may be  selected in a random drawing from among all remaining eligible entries.  Travel companion of winner will also be  required to sign a travel liability waiver. Noncompliance  will result in disqualification and an alternate winner may be selected.<strong>  </strong><strong><u>The prize will be awarded within  approximately 45 days after the winner is verified.<br />
  </u></strong><strong><br />
</strong><strong>PRIZE CONDITIONS:</strong>  All travel-related expenses included but not  limited to ground transportation to and from home to the major US airport,  taxes, gratuities, incidentals, upgrades, insurance, service charges, airport  surcharges<em>,</em> departure taxes, hotel,  resort or property fees, food &amp; beverage and personal expenses such as  telephone/Internet charges, and gift shop purchases are the sole responsibility  of prize winner and guest.  Accommodation  is based on two (2) guests sharing one (1) hotel room and a valid credit or  debit card will be required to guarantee any incidentals on check in.  All elements of the prize are subject to  availability; once confirmed, the prize cannot be amended or cancelled.  <strong>Winner and guest must have valid photo ID and  passport prior to departure</strong> and passport must be  valid for at least 6 months as of the date of travel, any necessary visas or  insurance are the responsibility of the winner and guests.  Prize cannot be taken over Christmas, New  Year, Thanksgiving or on US or Dutch public holidays and stay must include a  Saturday night.  Prize is valid for twelve  (12) months from date of notification of winning and all travel must be completed  within that time. Exact color of tulips may vary. Winner and guest must travel on same itinerary. </p>
<p>All hotel reservations are based on availability  and all holidays are excluded. Accommodations are subject to availability at  time of reservation. Blackout dates, advance booking requirements and travel  restrictions may apply. Availability is subject to factors such as weather,  seasonality and space availability. Reservations are subject to availability.  If weather affects the ability for winner and his/her guest to redeem any  portion of prize during the scheduled date and time, then the Sponsor shall  have no further obligation to the winner and/or guest other than to supply the  remaining elements of the prize package minus the unused portion of prize. If  for any reason whatsoever, winner and/or guest are unable to travel after all  travel arrangements have been made and paid, the Sponsor shall have no further  obligation to the winner. If Grand Prize is forfeited prior to Sponsor  finalizing and paying for travel, and there is sufficient time to notify an  alternate winner, the prize will be awarded to an alternate winner in a  separate random drawing from among all non-winning eligible entries. Winner and  guest are responsible for obtaining the proper travel documentation (e.g.,  valid photo ID) prior to travel. Winner&rsquo;s guest must be legal U.S. resident, 21 years or older and  must complete and return a Liability/Publicity/Travel Release prior to travel  as noted above. </p>
<p>If  a prize notification or prize is returned as undeliverable, or if winner is  found to be ineligible or not in compliance with these rules that winner will  be disqualified, and the prize may be awarded to an alternate winner in a  separate random drawing. </p>
<p>Prizes are not redeemable for cash. Prizes are  non-assignable or transferable. No substitution is permitted except if prize is  unavailable, in which case a prize of equal or greater value will be awarded.  No cash in lieu of prizes and no exchange or substitution of prizes, except at  the sole discretion of the Sponsor.Any other  incidental expenses on prize not specified herein are the winner&rsquo;s sole  responsibility.</p>
<p>Except  where prohibited by law, entry and acceptance of prize constitute permission to  use winner's name, prize won, hometown, likeness, video tape, photographs, and  statements for purposes of advertising, promotion and publicity (including  online posting) in any and all media now or hereafter known throughout the  world in perpetuity, without additional compensation, notification or  permission.<br />
  <br />
  Prizes are awarded &ldquo;as is&rdquo; with no warranty or guarantee, either express or  implied by Sponsor.  Winner acknowledges  that the Sponsor and all other businesses affiliated with this Sweepstakes and  their agents do not make, nor are in any manner responsible for any warranty,  representations, expressed or implied, in fact or in law, relative the quality,  conditions, fitness or merchantability of any aspect of the prize being offered,  except that each merchandise prize shall be subject to its manufacturer&rsquo;s  standard warranty (if any). <br />
  <br />
  <strong>GENERAL:</strong> Participating entrants agree to these Official Rules and the decisions of the  Sponsor, and release the Sweepstakes Entities and its affiliated companies, and  all other businesses involved in this Sweepstakes, as well as the employees,  officers, directors and agents of each, from all claims and liability relating  to their participation in the Sweepstakes, and the acceptance and use/misuse of  the prize offered. Winner assumes all liability for any injury or damage caused  or claimed to be caused, by participation in this Sweepstakes or use/misuse or  redemption of the prize. Sponsor is not responsible for any typographical or  other error in the printing of the offer, administration of the Sweepstakes or  in the announcement of the prize.  <br />
  Although  subsequent attempts to enter on a given day may be received, only the first  complete entry received from a particular entrant will be eligible; subsequent  attempts by the same person to enter, including entries submitted with an  alternate wireless telephone number, will be disqualified<br />
  <br />
  If for any reason this Sweepstakes is not capable of running as planned due to  an infection by a computer virus, bugs, tampering, unauthorized intervention,  fraud, technical failures, or any other causes beyond the control of the  Sponsor which corrupt or affect the administration, security, fairness,  integrity, or proper conduct of this Sweepstakes, the Sponsor reserves the right  at its sole discretion, to disqualify any individual who tampers with the entry  process, and to cancel, terminate, modify or suspend the Sweepstakes, at which  time, Sponsor will conduct a random drawing from among all eligible entries  received at the time of the Sweepstakes termination. The Sponsor assumes no  responsibility for any error, omission, interruption, deletion, defect, delay  in operation or transmission, communications line failure, theft or destruction  or unauthorized access to, or alteration of, entries. The Sponsor is not  responsible for any problems or technical malfunctions of any telephone and/or  wireless network or telephone lines, computer on-line or wireless mobile device  systems, servers, or providers, computer or mobile equipment, software, failure  of any e-mail or entry to be received by the Sponsor due to technical problems,  human error or traffic congestion on the Internet or at any Web site, or any  combination thereof, including any injury or damage to participant&rsquo;s or any  other person&rsquo;s computer or mobile device relating to or resulting from  participating in this Sweepstakes or downloading any materials in this  Sweepstakes.  Sponsor is not responsible  for incompatibility of entrant&rsquo;s hardware, software or browser technology.<br />
  <br />
  In  the event of a dispute over the identity of an online entrant, entry will be  deemed submitted by the &quot;Authorized Account Holder&quot; of the email  address submitted at time of entry. Authorized Account Holder means the natural  person who is assigned to an email address by an Internet access provider,  online service provider, or other organization that is responsible for  assigning e-mail addresses for the domain associated with the submitted e-mail  address.  Sponsor may ask any entrant or  potential winner to provide Sponsor with proof that such party is the  authorized account holder of the wireless phone associated with the entry.  Entry materials/data that have been tampered  with or altered, or mass entries or entries generated by a script, macro or use  of automated devices are void. The Sponsor is not responsible for: (i) error,  omission, interruption, deletion, defect, delay in operations or transmission,  theft or destruction or unauthorized access to or alterations of entry  materials, or for technical, network, telephone equipment, electronic,  computer, mobile device, hardware or software malfunctions of any kind, or  inaccurate transmission of or failure to receive entry information by Sponsor  on account of technical problems or traffic congestion on the Internet or at  any web site or any combination thereof; or (ii) any injury or damage to  entrant's or any other person's computer related to or resulting from  participating in the Sweepstakes. By participating in the Sweepstakes, you (i)  agree to be bound by these official rules, including all eligibility  requirements, and (ii) agree to be bound by the decisions of Sponsor and the  independent sweepstakes administrator, which are final and binding in all  matters relating to the Sweepstakes. Failure to comply with these official  rules may result in disqualification from the Sweepstakes. Sponsor reserves the  right to: (i) permanently disqualify from any Sweepstakes it sponsors any  person it believes has intentionally violated these official rules; and (ii)  withdraw the online method of entry if it becomes technically corrupted  (including if a computer virus or system malfunction inalterably impairs its  ability to conduct the Sweepstakes), and to select winners from among all  eligible entries received prior to withdrawal.<br />
  ANY ATTEMPT BY AN  INDIVIDUAL, WHETHER OR NOT AN ENTRANT, TO DELIBERATELY DAMAGE, DESTROY, TAMPER  OR VANDALIZE THE WEB SITE OR APP SITE<strong> </strong>OR  INTERFERE WITH THE OPERATION OF THE SWEEPSTAKES, IS A VIOLATION OF CRIMINAL AND  CIVIL LAWS AND SPONSOR RESERVES THE RIGHT TO SEEK DAMAGES AND DILIGENTLY PURSUE  ALL REMEDIES AGAINST ANY SUCH INDIVIDUAL TO THE FULLEST EXTENT PERMITTED BY  LAW.</p>
<p><a name="_DV_C7" id="_DV_C7"><strong>THE PROMOTION  AND ALL </strong></a><strong>PRIZES ARE <a name="_DV_C9" id="_DV_C9">PROVIDED</a> &ldquo;AS IS,&rdquo; SUBJECT ONLY TO ANY APPLICABLE  MANUFACTURER&rsquo;S WARRANTIES.  SWEEPSTAKES  ENTITIES, THE SWEEPSTAKES CENTER, AND THEIR RESPECTIVE DIRECTORS, OFFICERS,  EMPLOYEES, AND AGENTS MAKE NO WARRANTY OF ANY KIND WHATSOEVER, WHETHER  EXPRESSED OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR PURPOSE  WITH RESPECT  TO THE PRIZES AWARDED HEREUNDER<a name="_DV_C10" id="_DV_C10"></a><a name="_DV_X35" id="_DV_X35"> OR NON-INFRINGEMENT. SOME JURISDICTIONS MAY NOT  ALLOW THE LIMITATIONS OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL  DAMAGES OR EXCLUSION OF IMPLIED WARRANTIES SO SOME OF THE ABOVE LIMITATIONS OR  EXCLUSIONS MAY NOT APPLY TO YOU. CHECK YOUR LOCAL LAWS FOR ANY RESTRICTIONS OR  LIMITATIONS REGARDING THESE LIMITATIONS OR EXCLUSIONS</a>.</strong></p>
<p><a name="_DV_M30" id="_DV_M30"></a><strong>TECHNOLOGY  CONDITIONS</strong>:  The Sweepstakes Entities assume no responsibility for any damage to a  Participant's computer, mobile device or telephone system that is directly or  indirectly caused by accessing the Website or otherwise participating in the  Promotion, or for any computer system, mobile device operating or other system,  phone line, hardware, software or program malfunctions, or other errors,  failures, dropped or delayed computer or wireless transmissions or network  connections that are human or technical in nature. The Website's database clock  will be the official timekeeper for this Promotion. Once submitted, subject to  the Website&rsquo;s terms of use, entries become the property of the Sponsor. Except  as otherwise provided in these Official Rules, information collected in  connection with the Promotion will be used by Sponsor in accordance with Fox&rsquo;s  online privacy policy, located at http://www.foxconnect.com/privacy_policy.  Entry in the Promotion must be made by the  Participant and only at the Website or App Site. </p>
<p><strong>DISQUALIFICATION</strong>: It is the  Participant's responsibility to ensure compliance in all respects with these  Official Rules. Sponsor reserves the right in its sole discretion to prohibit a  Participant from participating in the Promotion or winning a prize if, in its  sole discretion, it determines that said Participant is attempting to undermine  the legitimate operation of this Promotion, including without limitation by  actually or attempting to: tamper with the entry processes or the operation of  the Promotion; act in violation of these Official Rules; act in an  unsportsmanlike or disruptive manner, or with the intent to disrupt or  undermine the legitimate operation of the Promotion, or to annoy, abuse,  threaten or harass any other person. Sponsor reserves the right to seek damages  and other remedies from any such person to the fullest extent permitted by law. <a name="_DV_M34" id="_DV_M34"></a></p>
<p><strong>FORCE MAJEURE</strong>: Sponsor  reserves the right, without prior notice and at any time, to terminate the  Promotion, in whole or in part, or modify or suspend the Promotion in any way,  if it determines, in its sole discretion, that the Promotion is technically  impaired or corrupted or that fraud or technical problems, failures or  malfunctions have destroyed or severely undermined the integrity and/or  feasibility of the Promotion. In the event Sponsor is prevented from continuing  with the Promotion as contemplated herein by any event beyond its reasonable  control, including but not limited to fire, flood, natural or man-made epidemic  of health or other means, earthquake, explosion, labor dispute or strike, act  of God or public enemy, satellite or equipment failure, riot or civil disturbance,  terrorist threat or activity, war (declared or undeclared) or any federal,  state or local government law, order, or regulation, public health crisis,  order of any court or jurisdiction, or other cause not reasonably within  Sponsor's control (each a &quot;Force Majeure&quot; event or occurrence), then  subject to any governmental approval which may be required, Sponsor shall have  the right to modify, suspend, or terminate the Promotion. If the Promotion is  terminated, in whole or in part, before the designated end date, Sponsor  reserves the right to select the winner from among all eligible, non-suspect  Entries received as of the date/time of the event giving rise to the  termination. <a name="_DV_M35" id="_DV_M35"></a>Only the type and quantity of prizes  described in these Official Rules will be awarded. </p>
<p><strong>INVALIDITY</strong>: These  Official Rules cannot be modified or amended in any way except in a written  document issued in accordance with law by a duly authorized representative of  Sponsor. The invalidity or unenforceability of any provision of these Official  Rules shall not affect the validity or enforceability of any other provision.  In the event that any provision is determined to be invalid or otherwise  unenforceable or illegal, these Official Rules shall otherwise remain in effect  and shall be construed in accordance with their terms as if the invalid or  illegal provision were not contained herein. In the event there is a  discrepancy or inconsistency between disclosures or other statements contained  in any Promotion materials and the terms and conditions of these Official  Rules, these Official Rules shall prevail, govern and control.<a name="_DV_M36" id="_DV_M36"></a></p>
<p><strong>GOVERNING LAW</strong>: All issues  and questions concerning the construction, validity, interpretation and  enforceability of these Official Rules or the rights and obligations of the  Participant, or Sponsor in connection with the Promotion shall be governed by  and construed in accordance with the internal laws of the State of California  without giving effect to any choice of law or conflict of law rules or  provisions that would cause the application of any other state's laws.  By participating in this Promotion,  Participants agree that California courts shall have jurisdiction over any  dispute or litigation arising from or relating to this Promotion and that venue  shall be only in Los Angeles, California. Any such controversy or claim shall  be litigated on an individual basis, and shall not be consolidated with any  claim or controversy of any other party.</p>
<p><a name="_DV_M37" id="_DV_M37"></a><strong>PRIVACY:</strong>  Information collected from online entrants is  subject to Sponsor&rsquo;s privacy policy, which can be found at http://www.foxconnect.com/privacy_policy. </p>
<p><strong>WINNERS LIST: </strong>To receive an  Official Winner&rsquo;s List for the Promotion, send a self-addressed stamped  envelope to: <em>The Fault In Our Stars </em>Home  Entertainment Sweepstakes Winner&rsquo;s List Request, PO Box 16350, Rochester, NY  14616. The Winners List request must be received by November 4, 2014, and it will  be fulfilled following the awarding of the prizes.</p>
<p><a name="_DV_M38" id="_DV_M38"></a><strong>OFFICIAL  RULES:</strong> To receive a copy of these Official Rules visit <a href="http://thefaultinourstarsmovie.com/">http://thefaultinourstarsmovie.com/</a>,  or mail a self-addressed stamped envelope to: <em>The Fault In Our Stars </em>Home Entertainment Sweepstakes Rules  Request, PO Box 16350, Rochester, NY 14616. Official Rules Request must be received  by October 7, 2014.</p>
<a name="_DV_M39" id="_DV_M39"></a><strong>SPONSOR:</strong> Twentieth  Century Fox Home Entertainment LLC, P.O. Box 900, Beverly Hills, CA 90214
</div>
</body>
</html>
